name = "signaaf"
main = ".open-next/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "signaaf"

[images]
binding = "IMAGES"

[vars]
NEXT_PUBLIC_POSTHOG_KEY = "phc_DosVqZCDFVNghfXCfLQBHG5ZpntSRmzrJZRzhKLMqTkh"
NEXT_PUBLIC_POSTHOG_HOST = "https://us.i.posthog.com"
